package com.andreenkomv.hibernate;
// Generated 28.11.2014 20:21:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Acts generated by hbm2java
 */
public class Acts  implements java.io.Serializable {


     private Integer id;
     private Parts parts;
     private Set favoriteses = new HashSet(0);
     private Set histories = new HashSet(0);

    public Acts() {
    }

	
    public Acts(Parts parts) {
        this.parts = parts;
    }
    public Acts(Parts parts, Set favoriteses, Set histories) {
       this.parts = parts;
       this.favoriteses = favoriteses;
       this.histories = histories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Parts getParts() {
        return this.parts;
    }
    
    public void setParts(Parts parts) {
        this.parts = parts;
    }
    public Set getFavoriteses() {
        return this.favoriteses;
    }
    
    public void setFavoriteses(Set favoriteses) {
        this.favoriteses = favoriteses;
    }
    public Set getHistories() {
        return this.histories;
    }
    
    public void setHistories(Set histories) {
        this.histories = histories;
    }




}


