package com.andreenkomv.hibernate;
// Generated 28.11.2014 20:21:44 by Hibernate Tools 4.3.1



/**
 * Favorites generated by hbm2java
 */
public class Favorites  implements java.io.Serializable {


     private Integer id;
     private Acts acts;
     private Users users;

    public Favorites() {
    }

    public Favorites(Acts acts, Users users) {
       this.acts = acts;
       this.users = users;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Acts getActs() {
        return this.acts;
    }
    
    public void setActs(Acts acts) {
        this.acts = acts;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


