package com.andreenkomv.hibernate;
// Generated 28.11.2014 20:21:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Parts generated by hbm2java
 */
public class Parts  implements java.io.Serializable {


     private Integer id;
     private int parent;
     private String name;
     private Set actses = new HashSet(0);

    public Parts() {
    }

	
    public Parts(int parent, String name) {
        this.parent = parent;
        this.name = name;
    }
    public Parts(int parent, String name, Set actses) {
       this.parent = parent;
       this.name = name;
       this.actses = actses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getParent() {
        return this.parent;
    }
    
    public void setParent(int parent) {
        this.parent = parent;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getActses() {
        return this.actses;
    }
    
    public void setActses(Set actses) {
        this.actses = actses;
    }




}


