package com.andreenkomv.hibernate;
// Generated 28.11.2014 20:21:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Texts generated by hbm2java
 */
public class Texts  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String text;
     private Set histories = new HashSet(0);

    public Texts() {
    }

	
    public Texts(String name, String text) {
        this.name = name;
        this.text = text;
    }
    public Texts(String name, String text, Set histories) {
       this.name = name;
       this.text = text;
       this.histories = histories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Set getHistories() {
        return this.histories;
    }
    
    public void setHistories(Set histories) {
        this.histories = histories;
    }




}


